target-version = "py311"
line-length = 88
src = ["src"]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "**/__pycache__",
    "*.pyc",
]

[lint]
select = [
    "E", "W", "F", "I", "UP", "B", "N", "C4", "SIM",
]
ignore = []
per-file-ignores = { "scripts/**" = ["E501"] }

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"